// styles/TabNavigationStyles.js (Updated with Watched Movies Styles)
import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const tabStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#1a1a1a',
    },
    content: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingBottom: 120,
    },
    movieCard: {
        width: '90%',
        maxWidth: 350,
        borderRadius: 20,
        overflow: 'hidden',
        marginTop: 50,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.3,
        shadowRadius: 20,
    },
    moviePoster: {
        width: '100%',
        height: 500,
        backgroundColor: '#3a3a3a',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 15,
        overflow: 'hidden',
    },
    posterImage: {
        width: 350,
        height: 500,
    },
    posterPlaceholder: {
        fontSize: 16,
        color: '#888',
        textAlign: 'center',
    },
    movieInfo: {
        padding: 20,
        justifyContent: "flex-end"
    },
    movieTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#fff',
        textAlign: 'center',
        marginBottom: 20,
    },
    actionButtons: {
        flexDirection: 'row',
        justifyContent: 'space-evenly',
        alignItems: 'center',
        marginVertical: 10,
    },
    watchedButton: {
        backgroundColor: '#4A90E2',
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 25,
    },
    addButton: {
        backgroundColor: '#333',
        width: 50,
        height: 50,
        borderRadius: 25,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: '#555',
    },
    didntWatchButton: {
        backgroundColor: '#E53E3E',
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 25,
    },
    tabBar: {
        position: 'absolute',
        bottom: 30,
        left: 20,
        right: 20,
        backgroundColor: '#2a2a2a',
        borderRadius: 25,
        paddingVertical: 15,
        paddingHorizontal: 10,
        flexDirection: 'row',
        justifyContent: 'space-around',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.25,
        shadowRadius: 10,
    },
    tabItem: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 8,
        paddingHorizontal: 12,
        borderRadius: 15,
        minWidth: 50,
    },
    activeTabItem: {
        backgroundColor: 'rgba(255, 255, 255, 0.15)',
    },
    tabIcon: {
        color: '#888',
    },
    activeTabIcon: {
        color: '#fff',
    },
    screenTitle: {
        fontSize: 28,
        fontWeight: 'bold',
        color: '#fff',
        marginBottom: 20,
    },
    screenContent: {
        fontSize: 16,
        color: '#ccc',
        textAlign: 'center',
        lineHeight: 24,
    },
    logoutButton: {
        backgroundColor: '#dc3545',
        paddingVertical: 12,
        paddingHorizontal: 30,
        borderRadius: 8,
        marginTop: 30,
    },
    logoutButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    userInfo: {
        backgroundColor: '#2a2a2a',
        padding: 15,
        borderRadius: 10,
        marginBottom: 20,
        borderWidth: 1,
        borderColor: '#444',
        minWidth: '80%',
    },
    userEmail: {
        fontSize: 14,
        color: '#fff',
        textAlign: 'center',
    },

    watchedScrollView: {
        flex: 1,
        width: '100%',
    },
    watchedScrollContent: {
        paddingHorizontal: 10,
        paddingBottom: 20,
    },
    watchedList: {
        width: '100%',
        paddingHorizontal: 10,
    },
    watchedItem: {
        flexDirection: 'row',
        backgroundColor: '#2a2a2a',
        borderRadius: 15,
        padding: 15,
        marginBottom: 15,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 5 },
        shadowOpacity: 0.2,
        shadowRadius: 10,
    },
    watchedPoster: {
        width: 80,
        height: 120,
        borderRadius: 10,
        overflow: 'hidden',
        backgroundColor: '#3a3a3a',
        justifyContent: 'center',
        alignItems: 'center',
    },
    watchedPosterImage: {
        width: '100%',
        height: '100%',
    },
    watchedPosterPlaceholder: {
        width: '100%',
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#3a3a3a',
    },
    posterPlaceholderText: {
        fontSize: 12,
        color: '#888',
        textAlign: 'center',
    },
    watchedInfo: {
        flex: 1,
        marginLeft: 15,
        justifyContent: 'space-between',
    },
    watchedHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 10,
    },
    watchedTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#fff',
        lineHeight: 22,
        flex: 1,
        marginRight: 10,
    },
    deleteButton: {
        borderRadius: 15,
        width: 30,
        height: 30,
        justifyContent: 'center',
        alignItems: 'center',
    },
    watchedRating: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 15,
    },
    ratingText: {
        color: '#ccc',
        fontSize: 14,
        marginLeft: 8,
    },
    favoriteButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#333',
        paddingVertical: 8,
        paddingHorizontal: 12,
        borderRadius: 8,
        alignSelf: 'flex-start',
    },
    favoriteText: {
        fontSize: 14,
        marginLeft: 6,
        fontWeight: '500',
    },
});