// styles/TabNavigationStyles.js (Updated with Favorites Styles)
import { StyleSheet, Dimensions } from 'react-native';

const { width } = Dimensions.get('window');

export const tabStyles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#1a1a1a',
    },
    content: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingBottom: 120,
    },
    movieCard: {
        width: '90%',
        maxWidth: 350,
        borderRadius: 20,
        overflow: 'hidden',
        marginTop: 50,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.3,
        shadowRadius: 20,
    },
    moviePoster: {
        width: '100%',
        height: 500,
        backgroundColor: '#3a3a3a',
        justifyContent: 'center',
        alignItems: 'center',
        borderRadius: 15,
        overflow: 'hidden',
    },
    posterImage: {
        width: 350,
        height: 500,
    },
    posterPlaceholder: {
        fontSize: 16,
        color: '#888',
        textAlign: 'center',
    },
    movieInfo: {
        padding: 20,
        justifyContent: "flex-end"
    },
    movieTitle: {
        fontSize: 24,
        fontWeight: 'bold',
        color: '#fff',
        textAlign: 'center',
        marginBottom: 20,
    },
    actionButtons: {
        flexDirection: 'row',
        justifyContent: 'space-evenly',
        alignItems: 'center',
        marginVertical: 10,
    },
    watchedButton: {
        backgroundColor: '#4A90E2',
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderRadius: 25,
    },
    addButton: {
        backgroundColor: '#E53E3E',
        width: 50,
        height: 50,
        borderRadius: 25,
        justifyContent: 'center',
        alignItems: 'center',
        borderWidth: 2,
        borderColor: '#E53E3E',
    },
    addButtonFavorited: {
        backgroundColor: '#E53E3E',
        borderColor: '#E53E3E',
    },
    didntWatchButton: {
        backgroundColor: '#666',
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 12,
        paddingHorizontal: 16,
        borderRadius: 25,
    },
    tabBar: {
        position: 'absolute',
        bottom: 30,
        left: 20,
        right: 20,
        backgroundColor: '#2a2a2a',
        borderRadius: 25,
        paddingVertical: 15,
        paddingHorizontal: 10,
        flexDirection: 'row',
        justifyContent: 'space-around',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.25,
        shadowRadius: 10,
    },
    tabItem: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingVertical: 8,
        paddingHorizontal: 12,
        borderRadius: 15,
        minWidth: 50,
    },
    activeTabItem: {
        backgroundColor: 'rgba(255, 255, 255, 0.15)',
    },
    tabIcon: {
        color: '#888',
    },
    activeTabIcon: {
        color: '#fff',
    },
    screenTitle: {
        fontSize: 28,
        fontWeight: 'bold',
        color: '#fff',
        marginBottom: 20,
    },
    screenContent: {
        fontSize: 16,
        color: '#ccc',
        textAlign: 'center',
        lineHeight: 24,
    },
    logoutButton: {
        backgroundColor: '#519EF6',
        paddingVertical: 12,
        paddingHorizontal: 67,
        borderRadius: 8,
        marginTop: 30,
    },
    logoutButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    userInfo: {
        backgroundColor: '#2a2a2a',
        padding: 15,
        borderRadius: 10,
        marginBottom: 20,
        borderWidth: 1,
        borderColor: '#444',
        minWidth: '80%',
    },
    userEmail: {
        fontSize: 14,
        color: '#fff',
        textAlign: 'center',
    },

    watchedScrollView: {
        flex: 1,
        width: '100%',
    },
    watchedScrollContent: {
        paddingHorizontal: 10,
        paddingBottom: 20,
    },
    watchedList: {
        width: '100%',
        paddingHorizontal: 10,
    },
    watchedItem: {
        flexDirection: 'row',
        backgroundColor: '#2a2a2a',
        borderRadius: 15,
        padding: 15,
        marginBottom: 15,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 5 },
        shadowOpacity: 0.2,
        shadowRadius: 10,
    },
    watchedPoster: {
        width: 80,
        height: 120,
        borderRadius: 10,
        overflow: 'hidden',
        backgroundColor: '#3a3a3a',
        justifyContent: 'center',
        alignItems: 'center',
    },
    watchedPosterImage: {
        width: '100%',
        height: '100%',
    },
    watchedPosterPlaceholder: {
        width: '100%',
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#3a3a3a',
    },
    posterPlaceholderText: {
        fontSize: 12,
        color: '#888',
        textAlign: 'center',
    },
    watchedInfo: {
        flex: 1,
        marginLeft: 15,
        justifyContent: 'space-between',
    },
    watchedHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 10,
    },
    watchedTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#fff',
        lineHeight: 22,
        flex: 1,
        marginRight: 10,
    },
    deleteButton: {
        borderRadius: 15,
        width: 30,
        height: 30,
        justifyContent: 'center',
        alignItems: 'center',
    },
    watchedRating: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 15,
    },
    ratingText: {
        color: '#ccc',
        fontSize: 14,
        marginLeft: 8,
    },
    favoriteButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#333',
        paddingVertical: 8,
        paddingHorizontal: 12,
        borderRadius: 8,
        alignSelf: 'flex-start',
    },
    favoriteText: {
        fontSize: 14,
        marginLeft: 6,
        fontWeight: '500',
    },
    favoriteIndicator: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#333',
        paddingVertical: 8,
        paddingHorizontal: 12,
        borderRadius: 8,
        alignSelf: 'flex-start',
    },
    favoriteIndicatorText: {
        fontSize: 14,
        marginLeft: 6,
        fontWeight: '500',
        color: '#E53E3E',
    },

    // Favorites Grid Styles
    favoritesScrollView: {
        flex: 1,
        width: '100%',
    },
    favoritesScrollContent: {
        paddingHorizontal: 10,
        paddingBottom: 20,
    },
    favoritesGrid: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        justifyContent: 'space-between',
        width: '100%',
    },
    favoriteItem: {
        width: '48%',
        marginBottom: 15,
    },
    favoritePoster: {
        width: '100%',
        height: 220,
        borderRadius: 12,
        overflow: 'hidden',
        backgroundColor: '#3a3a3a',
        position: 'relative',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
    },
    favoritePosterImage: {
        width: '100%',
        height: '100%',
    },
    favoritePosterPlaceholder: {
        width: '100%',
        height: '100%',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#3a3a3a',
    },
    favoritePlaceholderText: {
        fontSize: 12,
        color: '#888',
        textAlign: 'center',
    },
    favoriteDeleteButton: {
        position: 'absolute',
        top: 8,
        right: 8,
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
        borderRadius: 15,
        width: 30,
        height: 30,
        justifyContent: 'center',
        alignItems: 'center',
    },
    deleteAccountButton: {
        backgroundColor: '#dc3545',
        paddingVertical: 12,
        paddingHorizontal: 30,
        borderRadius: 8,
        marginTop: 15,
        borderWidth: 2,
        borderColor: '#dc3545',
    },
    deleteAccountButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
        textAlign: 'center',
    },
    deleteAccountButton: {
        backgroundColor: '#dc3545',
        paddingVertical: 12,
        paddingHorizontal: 30,
        borderRadius: 8,
        marginTop: 15,
        borderWidth: 2,
        borderColor: '#dc3545',
    },
    deleteAccountButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
        textAlign: 'center',
    },

    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.7)',
        justifyContent: 'center',
        alignItems: 'center',
    },
    modalContainer: {
        backgroundColor: '#2a2a2a',
        borderRadius: 20,
        padding: 25,
        width: '85%',
        maxWidth: 400,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 10 },
        shadowOpacity: 0.3,
        shadowRadius: 20,
        elevation: 10,
    },
    modalTitle: {
        fontSize: 22,
        fontWeight: 'bold',
        color: '#fff',
        textAlign: 'center',
        marginBottom: 10,
    },
    modalSubtitle: {
        fontSize: 16,
        color: '#ccc',
        textAlign: 'center',
        marginBottom: 20,
        lineHeight: 22,
    },
    modalInput: {
        backgroundColor: 'rgba(255, 255, 255, 0.95)',
        paddingHorizontal: 15,
        paddingVertical: 12,
        borderRadius: 10,
        fontSize: 16,
        marginBottom: 20,
        borderWidth: 1,
        borderColor: '#444',
    },
    modalButtons: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        gap: 10,
    },
    modalCancelButton: {
        flex: 1,
        backgroundColor: '#444',
        paddingVertical: 12,
        borderRadius: 10,
    },
    modalDeleteButton: {
        flex: 1,
        backgroundColor: '#dc3545',
        paddingVertical: 12,
        borderRadius: 10,
    },
    modalCancelText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
        textAlign: 'center',
    },
    modalDeleteText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
        textAlign: 'center',
    },
    // Estilos para a tela "Adicionar Filme"
    addMovieScrollView: {
        flex: 1,
        width: '100%',
    },
    addMovieScrollContent: {
        paddingHorizontal: 20,
        paddingBottom: 40,
    },
    formContainer: {
        width: '100%',
    },
    inputGroup: {
        marginBottom: 20,
    },
    inputLabel: {
        fontSize: 16,
        fontWeight: '600',
        color: '#fff',
        marginBottom: 8,
    },
    textInput: {
        backgroundColor: 'rgba(255, 255, 255, 0.1)',
        borderWidth: 1,
        borderColor: '#444',
        borderRadius: 10,
        paddingHorizontal: 15,
        paddingVertical: 12,
        fontSize: 16,
        color: '#fff',
        minHeight: 48,
    },

    // Preview Section
    previewSection: {
        marginTop: 20,
        marginBottom: 30,
    },
    previewTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#fff',
        marginBottom: 15,
    },
    previewCard: {
        flexDirection: 'row',
        backgroundColor: '#2a2a2a',
        borderRadius: 15,
        padding: 15,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 5 },
        shadowOpacity: 0.2,
        shadowRadius: 10,
    },
    previewPoster: {
        width: 80,
        height: 120,
        borderRadius: 10,
        overflow: 'hidden',
        backgroundColor: '#3a3a3a',
        justifyContent: 'center',
        alignItems: 'center',
    },
    previewPosterImage: {
        width: '100%',
        height: '100%',
    },
    previewInfo: {
        flex: 1,
        marginLeft: 15,
        justifyContent: 'center',
    },
    previewMovieTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: '#fff',
    },

    // Action Buttons
    actionButtonsContainer: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        marginTop: 20,
        gap: 15,
    },
    clearButton: {
        flex: 1,
        backgroundColor: '#444',
        paddingVertical: 15,
        borderRadius: 10,
        alignItems: 'center',
    },
    clearButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
    },
    addMovieButton: {
        flex: 2,
        backgroundColor: '#4A90E2',
        paddingVertical: 15,
        borderRadius: 10,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
    },
    addMovieButtonDisabled: {
        backgroundColor: '#666',
        opacity: 0.6,
    },
    addMovieButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '600',
    },
    movieSource: {
        fontSize: 14,
        color: '#4A90E2',
        textAlign: 'center',
        marginBottom: 15,
        fontStyle: 'italic',
    },
});